version: "3.9"

services:

  deal-analyzer:

    build: .

    container_name: deal-analyzer

    ports:
      - "8501:8501"

    env_file:
      - .env

    volumes:
      - .:/app

    restart: unless-stopped